services:
  postgres-nexus:
    image: postgres:17.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nexus_writer
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_nexus_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus_user -d nexus_writer"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - nexus-network

  redis-nexus:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - redis_data:/data
    networks:
      - nexus-network
    command: redis-server --appendonly yes

  nexus-worker:
    build: .
    command: uv run celery -A app.worker worker --loglevel=info
    environment:
      REDIS_URL: redis://redis-nexus:6379/0
      REDIS_BROKER_URL: redis://redis-nexus:6379/1
    depends_on:
      postgres-nexus:
        condition: service_healthy
      redis-nexus:
        condition: service_healthy
    networks:
      - nexus-network

  nexus-writer:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://nexus_user:password@postgres-nexus:5432/nexus_writer
      REDIS_URL: redis://redis-nexus:6379/0
      REDIS_BROKER_URL: redis://redis-nexus:6379/1
    depends_on:
      postgres-nexus:
        condition: service_healthy
      redis-nexus:
        condition: service_healthy
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge

volumes:
  postgres_nexus_data:
  redis_data: